[package]
name = "aruaru-vpn"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "aruaru-vpn-keys"
path = "src/bin/keys_gui.rs"

[dependencies]
chacha20poly1305 = "0.11.0"
eframe = "0.32"
egui = "0.32"
hmac = "0.13.0"
rfd = "0.16.0"
hkdf = "0.13.0"
open-runo-tls-fingerprint = { git = "https://github.com/aon-co-jp/RPoem.git", package = "open-runo-tls-fingerprint" }
rand = "0.10.3"
rand_core = "0.10.1"
rcgen = "0.14.10"
rustls = "0.23.45"
sha2 = "0.11.0"
snow = "0.10.0"
tokio = { version = "1.53.1", features = ["net", "io-util", "rt-multi-thread", "macros", "sync", "time"] }
tokio-rustls = "0.26.5"
x25519-dalek = { version = "3.0.0", features = ["static_secrets"] }
